### ISSUE TITLE
Unable to connect (failed directory listing)

### ISSUE THREAD

**Issue by driici** [Castaglia/proftpd-mod_proxy#158] opened 2020-04-20 10:49 UTC
Hello
I have compiled latest proftpd with latest (but tried some older vesions of both) mod_proxy on debian 10 and having issues with connections

proftpd -V: https://pastebin.com/YwpkNXJU
proftpd.conf: https://pastebin.com/EQ3yKpv4 (redacted password backend connection string)

I have also another instance of proftpd with mod_proxy on older machine (debian 8) and it works flawlessly - firewall config is same, proftpd config is same also.

Strange thing is that some connections are done OK, some fails after directory listing (MLSD or LIST command). Backend connection succeeded according logs.
When listing fails, I was able to find some information from log, but not sure if they're relevant:
```
2020-04-20 12:40:18,950 mod_proxy/0.5[15455]: client sent RFC1918 address '10.8.0.2' in PORT command, ignoring it and using '46.36.xxx.xxx'
2020-04-20 12:40:19,538 mod_proxy/0.5[15455]: unable to connect to 46.36.xxx.xxx#0: Invalid argument
```
Is there any more informations I should provide? Thanks

**Comment by Castaglia** [comment] 2020-04-26 22:30
Can you provide all the logs that you can, for both successful _and_ failing directory listings?  I'm hoping to see what might be different between the success and failure cases...

**Comment by driici** [comment] 2020-04-28 13:18
Hi, thanks for your time. 
First connection in logs is failing, second one is OK. From my perspective I dont see much differences.

logs attached:
[ftp.zip](https://github.com/Castaglia/proftpd-mod_proxy/files/4545940/ftp.zip)

**Comment by Castaglia** [comment] 2020-05-01 02:07
Thanks for those.  Nothing standing out _just_ yet.  So, to get more data, would you mind adding more to your `Trace` directive?  Specifically:
```
  Trace proxy:30 \
    command:20 \
    proxy.conn:30 \
    proxy.db:30 \
    proxy.forward:30 \
    proxy.ftp.conn:30 \
    proxy.ftp.ctrl:30 \
    proxy.ftp.data:30 \
    proxy.ftp.msg:30 \
    proxy.ftp.sess:30 \
    proxy.ftp.xfer:30 \
    proxy.inet:30 \
    proxy.netio:30 \
    proxy.random:30 \
    proxy.reverse:30 \
    proxy.reverse.db:30 \
    proxy.reverse.redis:30 \
    proxy.session:30 \
    proxy.tls:30 \
    proxy.tls.db:30 \
    proxy.tls.redis:30 \
    proxy.uri:30 \
    response:20
```
And then provide the logs for a successful, and failed, directory listing?  Hopefully the increased logging will provide more clues.

**Comment by driici** [comment] 2020-05-04 10:34
Hi, hope these will help.
[proftpd.notworking.zip](https://github.com/Castaglia/proftpd-mod_proxy/files/4574085/proftpd.notworking.zip)
[proftpd.working.zip](https://github.com/Castaglia/proftpd-mod_proxy/files/4574087/proftpd.working.zip)

**Comment by Castaglia** [comment] 2020-05-25 22:22
Thanks for those; they do help.

In the not-working case, we see the "425 MLSD: Invalid argument" error response -- which can only come from [here](https://github.com/Castaglia/proftpd-mod_proxy/blob/master/mod_proxy.c#L2177), based on the rest of the logs provided.  And that, in turn, means that the [`proxy_ftp_conn_connect`](https://github.com/Castaglia/proftpd-mod_proxy/blob/master/mod_proxy.c#L2172) function here is the one returning the `EINVAL` error.

Looking at that function, we see that the only way the `proxy_ftp_conn_connect` function can return `EINVAL` -- without logging anything else, which we did *not* see in the provided logs -- is [here](https://github.com/Castaglia/proftpd-mod_proxy/blob/master/lib/proxy/ftp/conn.c#L101), suggesting that either `p` (a memory pool) _or_ `remote_addr` is null.  That `remote_addr` comes from the "client sent RFC1918 address, ignoring it" code path in this situation.  And there, a short-lived memory pool is used for that `remote_addr` object.

Based on this, I'm _guessing_ that [this PR](https://github.com/Castaglia/proftpd-mod_proxy/pull/159) might help?  I'll work on trying to reproduce this exact scenario locally, but in the meantime, wanted to see if you, too, could test out the patch/PR, and see if it helps.

**Comment by driici** [comment] 2020-06-08 07:06
Hello, sorry for delay. We had tested your commit, but have same issues.

**Comment by driici** [comment] 2020-07-07 06:26
BUMP

**Comment by Castaglia** [comment] 2020-07-07 20:24
@driici  If I cannot reproduce the issue locally, then I cannot easily address/fix this.  Barring that, I need _something_ that reliably shows this error, in order to fix it.

**Comment by Castaglia** [comment] 2020-07-18 19:18
@driici I'm hoping that https://github.com/Castaglia/proftpd-mod_proxy/commit/ebcf82c9f3e5668e2b0218712bba64ec3287d6be can also help to address this; can you try the latest `mod_proxy` code in your environment, and see if the issue has been addressed?

**Comment by aljasPOD** [comment] 2022-06-12 04:59
I've encountered a similar issue (and spent a few hours debugging).

In my case the EINVAL was coming from the linux connect call (all the way from [here](https://github.com/proftpd/proftpd/blob/b724aea82cf281447aae1f70f0a0e8eb4e79640c/src/inet.c#L1430)).

Doing strace on the running binary gives this: 
![image](https://user-images.githubusercontent.com/20117504/173215002-e495726a-0253-4cd9-817e-f34944b02277.png)
While some versions of connect's man document some cases of EINVAL, I have not found this specific case there.
It seems that the bind happens with an IPv6 (family) address, but the connect is with an IPv4. 

Setting the `ProxySourceAddress` to the (IPv4) address of the host fixes the problem, the bind happens with a v4 address and the connection succeeds.

**Comment by Castaglia** [comment] 2022-06-12 17:00
@aljasPOD thanks for digging into this!  This reminds me of some logging changes I recently did for Issue #213, namely to try to add logging hints in cases where `ProxySourceAddress` might be needed.  In the case of this other issue, the cause was a mismatch between public/privately routable IP addresses -- but this case here, of IPv6 _vs_ IPv4 is another such scenario.  I'll see about adding similar detection/logging, to try to make it clearer to admins what the solution might be.

**Comment by Castaglia** [comment] 2022-06-12 17:07
Interestingly, I _do_ see that `mod_proxy` attempts to handle such IPv6/IPv4 cases [here](https://github.com/Castaglia/proftpd-mod_proxy/blob/master/lib/proxy/conn.c#L700) -- but that's when establishing the backend control connection; when making the backend _data_ connection (as for file transfers, directory listings) [here](https://github.com/Castaglia/proftpd-mod_proxy/blob/master/lib/proxy/ftp/conn.c#L174), we are _not_ doing similar checking, and we should be.

**Comment by Castaglia** [comment] 2022-06-19 23:24
@driici Would you be able to test the latest `mod_proxy` code, to see if your issue still occurs?  Thanks!

**Comment by Castaglia** [comment] 2022-06-19 23:48
@driici Actually, in looking back through your logs with fresh eyes, I think the issue you encountered is _different_ than that of @aljasPOD.  The recent commits should make the behavior behavior for @aljasPOD -- but not for @driici.

Here's what I see, for @driici 's use case:
* Frontend FTP client connects to proxy, running on 46.36.37.xx; proxy selects backend of 46.36.39.xx
* Frontend FTP client sends `PORT 10.0.8.2` to proxy, which _should_ have rejected this sooner (since it means that client is saying "I contacted you, server on 46.36.37.xx, but I want you to connect to me on private IP space address 10.0.8.2" (which usually indicates a naive/badly behaving FTP client)
* Proxy, instead, sends EPSV command to backend (because of `ProxyDataTransferPolicy passive` configuration), which succeeds
* Proxy responds to frontend client's `PORT` command with 200 response, saying "Yes, that's OK" (and it should not have done this)
* Frontend FTP client sends `MLSD` command to start the directory listing -- and _that_ is when the proxy complains, since it cannot connect to the frontend client IP address 10.0.8.2.

I'll try to confirm the above hypothesis by reproducing the above behaviors locally.

**Comment by Castaglia** [comment] 2022-06-25 22:19
I've confirmed that `mod_proxy` does indeed properly reject `PORT`, `EPRT` commands that tell the server to use an IP address that is different than the client's IP address for the control connection.

I'd thus like to close this ticket, and we'll use new tickets for any more issues that arise.  Sound good?

**Closed** 2024-09-14 15:06 UTC
Labels: Waiting for feedback
