### ISSUE TITLE
Error on high load: database is locked

### ISSUE THREAD

**Issue by skirmis** [Castaglia/proftpd-mod_proxy#93] opened 2017-02-08 17:50 UTC
```
2017-02-08 17:41:42,064 mod_proxy/0.3[12955]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'xxxx': Operation not permitted
2017-02-08 17:41:42,064 mod_proxy/0.3[12955]: error selecting backend server: Operation not permitted
2017-02-08 17:41:44,467 mod_proxy/0.3[12986]: error executing 'INSERT INTO proxy_reverse.proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
2017-02-08 17:41:44,467 mod_proxy/0.3[12986]: error preparing database for ProxyReverseConnectPolicy PerUser for user 'xxxx': Operation not permitted
2017-02-08 17:41:44,467 mod_proxy/0.3[12986]: error selecting backend server: Operation not permitted
2017-02-08 17:41:45,287 mod_proxy/0.3[12994]: error executing 'INSERT INTO proxy_reverse.proxy_vhost_reverse_per_user (vhost_id, user_name, backend_uri) VALUES (?, ?, ?);': database is locked
```
 
Can you help me or suggest how to avoid Sqlite write locks? Thank you.

**Comment by Castaglia** [comment] 2017-02-08 18:00
Is it possible to provide more of that `ProxyLog` file's entries?  From reading the SQLite docs, the `SQLITE_LOCKED` error code is what's being logged.  And while we _could_ handle `SQLITE_LOCKED` just as we do for `SQLITE_BUSY`, [here](https://github.com/Castaglia/proftpd-mod_proxy/blob/master/lib/proxy/db.c#L83), I'm not sure that that would help, assuming that the cause of contention is from some _other_ code using the same database connection (which means from the same process).

So perhaps there's somewhere in your `ProxyLog` where these errors appear to start?

**Comment by skirmis** [comment] 2017-02-08 18:15
I can give you full log in private some how. Now seems mod_proxy works quite well according to high traffic and about 500 concurrent users logged in(can reach 1000 and more). Please say how I can send you log file. Locked database error is not very often, but happens time to time.

**Comment by Castaglia** [comment] 2017-02-08 18:19
You can send it to me via email if you like (`tj@castaglia.org`).  My public GPG key is available if you'd like to encrypt it.

**Comment by skirmis** [comment] 2017-02-08 19:08
Email with proxy.log have been sent. Thank you

**Comment by skirmis** [comment] 2017-02-08 19:37
It is possible to use redis or mysql instead of sqlite for mod_proxy itself?

**Comment by Castaglia** [comment] 2017-02-08 21:07
Not currently; as you found, there's a different ticket for that support.  I'm not sure how much work would be needed to make that work properly for `mod_proxy` yet.

**Comment by Castaglia** [comment] 2017-02-09 02:20
Could you configure a `TraceLog` for `mod_proxy`, pointing at the same file as your `ProxyLog`, for extra debugging?
```
    ProxyLog /var/log/proftpd/proxy.log
    TraceLog /var/log/proftpd/proxy.log
    Trace proxy:20 proxy.db:20
```
The additional trace logging _should_ include more verbose logging from SQLite itself, which (I'm hoping) will help illuminate the cause of those "Operation not permitted" errors.  Thanks!

**Comment by skirmis** [comment] 2017-02-09 08:58
wrote you an email with all details in it, thank you

**Comment by Castaglia** [comment] 2017-02-10 04:46
I'm able to reproduce your symptoms locally, using the latest `mod_proxy` source code and your provided configuration.

**Comment by skirmis** [comment] 2017-02-10 08:16
I have noticed another strange issue, ` mod_proxy ` cannot reach ipv6 backend(connection time out) without ` ProxySourceAddress ` ( server ipv6 address ). Ipv4 works well without ` ProxySourceAddress ` directive. With network everything is OK I assume.

**Comment by Castaglia** [comment] 2017-02-10 20:54
With this latest code merged, could you see if you still encounter your issues?  I am no longer able to reproduce the behavior locally with this change.

**Comment by skirmis** [comment] 2017-02-11 07:40
I will test it soon, thank you so much

**Comment by Castaglia** [comment] 2017-02-11 16:24
Hmm.  I spoke too soon; I'm still seeing some "database is locked" in my local regression testing, but now for different portions of the code.  Some more work will be needed on this.

**Comment by Castaglia** [comment] 2017-02-13 01:17
I ended up redoing mod_proxy's database API, mostly because I was finding it conceptually difficult to follow, mostly because I'd been using the `ATTACH`/`DETACH DATABASE` SQLite commands for syntactic sugar support -- and they were more of a hindrance than a help.

In the course of doing the above work, I also added more logging callbacks, in an effort to track down the culprit.  In the end, I _did_ find them.  _For each new session_, a table integrity check (via `PRAGMA integrity_check;`) *and* a vacuuming (via `VACUUM;`) where happening.  The vacuum, in particular, _would_ lock databases.  And these were unnecessary for sessions; the integrity check and vacuum had been intended to be run _only_ on startup.   Thus disabling those actions, per session, greatly reduced any "database is locked" contention.

With these changes, I _think_ this behavior should *now* be fixed.  I look forward to hearing whether you can confirm this.

**Comment by skirmis** [comment] 2017-02-13 10:39
Hello, yes I have tried your first fix, but without success(same errors on database locked). Now I'm compiling latest version and let you know about result soon. Thank you

**Comment by skirmis** [comment] 2017-02-13 10:48
Cannot compile source, got error:

make[1]: Leaving directory `/root/proftpd/modules'
    STDERR: lib/proxy/db.c: In function ‘db_sql’:
    lib/proxy/db.c:81:7: error: expected ‘;’ before ‘}’ token
           } else {
           ^
    make[2]: *** [lib/proxy/db.o] Error 1

**Comment by Castaglia** [comment] 2017-02-13 15:26
Doh!  I wonder why Travis didn't catch that; it was a missing semicolon, now fixed.

**Comment by skirmis** [comment] 2017-02-13 18:09
I successfully compiled and tested newest version. Locked database errors is gone. Everything was working much better and longer. But after logged user reached 92 everything started to fail with errors:
` 2017-02-13 17:56:56,642 mod_proxy/0.3[30939]: error selecting backend server: Invalid argument
2017-02-13 17:56:56,642 mod_proxy/0.3[30939]: error selecting backend server: Invalid argument `

seems database got corrupted and one thing that helps ` proftpd restart ` and after about 5 minutes happens again on production server :/

**Comment by skirmis** [comment] 2017-02-13 19:21
SQLite locks error have been fixed and are gone. This issue can be closed.

**Comment by Castaglia** [comment] 2017-02-13 19:33
Excellent.  Thanks for confirming!

**Closed by Castaglia** 2017-02-13 19:33 UTC
Labels: Bug
