### ISSUE TITLE
Forward proxy with TLS error on second/third command

### ISSUE THREAD

**Issue by andreasfenzsw** [Castaglia/proftpd-mod_proxy#87] opened 2016-10-21 09:41 UTC
Hello,

is set up a forward proxy. I can connect and do an "ls" but then the TLS connection fail.

Config:

```
<IfModule mod_proxy.c>
  ProxyEngine on
  ProxyLog /var/log/modproxy.log
  ProxyTables /usr/local/var/ftp/proxy
  ProxyRole forward
  ProxyForwardMethod user@host
  ProxyTLSEngine on
   ProxyTLSOptions EnableDiags
   ProxyTLSProtocol ALL -SSLv3 -TLSv1
   ProxyTLSVerifyServer off
  <Class forward-proxy>
      From 127.0.0.1/32
      ProxyForwardEnabled on
  </Class>
</IfModule>
```

commands:

```
230 User logged in.
Remote system type is xxx.
ftp> passive
Passive mode on.
ftp> ls
227 Entering Passive Mode (127,0,0,1,191,148).
150 Opening ASCII mode data connection.
drwxrwxrwx   1 owner    group               0 Jun 20 16:12 aaa
drwxrwxrwx   1 owner    group               0 Jun 20 15:50 bbbb
226-Directory has 42,983,424 bytes of disk space available.
226 Transfer complete.

ftp> ls
227 Entering Passive Mode (127,0,0,1,202,218).
150 Opening ASCII mode data connection.
```

this hang forever.

log:

```
2016-10-21 09:29:24,518 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:24,518 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:24,518 mod_proxy/0.3[50041]: [tls.info] ok: SSL negotiation finished successfully
2016-10-21 09:29:24,518 mod_proxy/0.3[50041]: [tls.info] connecting: SSL negotiation finished successfully
2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: Server: XXXXXX
2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: TLSv1.2 connection created, using cipher ECDHE-RSA-AES256-SHA384 (256 bits)
2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: passive backend data connection opened - local  : 46.16.73.69:39811
2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: passive backend data connection opened - remote : 212.21.67.209:5028
2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: passive frontend data connection opened - local  : 127.0.0.1:49044
2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: passive frontend data connection opened - remote : 127.0.0.1:44857
2016-10-21 09:29:24,548 mod_proxy/0.3[50041]: [tls.msg] received TLSv1.2 warning 'close_notify' Alert message (2 bytes)
2016-10-21 09:29:24,548 mod_proxy/0.3[50041]: [tls.info] reading: SSL/TLS alert warning: close notify
```
##### here i got the directory listing an issue an other "ls" command

```
2016-10-21 09:29:37,870 mod_proxy/0.3[50041]: Entering Passive Mode (127,0,0,1,202,218).
2016-10-21 09:29:37,935 mod_proxy/0.3[50041]: starting TLS negotiation on data connection
2016-10-21 09:29:37,935 mod_proxy/0.3[50041]: [tls.info] (unknown): before/connect initialization
2016-10-21 09:29:37,935 mod_proxy/0.3[50041]: [tls.info] connecting: before/connect initialization
2016-10-21 09:29:37,935 mod_proxy/0.3[50041]: [tls.msg] sent TLSv1.2 'ClientHello' Handshake message (512 bytes)
2016-10-21 09:29:37,935 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,935 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,974 mod_proxy/0.3[50041]: [tls.msg] received TLSv1.2 'ServerHello' Handshake message (81 bytes)
2016-10-21 09:29:37,974 mod_proxy/0.3[50041]: [tls.tlsext] TLS server extension "renegotiation info" (ID 65281, 1 byte)
2016-10-21 09:29:37,974 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,974 mod_proxy/0.3[50041]: [tls.msg] received TLSv1.2 ChangeCipherSpec message (1 byte)
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.msg] received TLSv1.2 'Finished' Handshake message (16 bytes)
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.msg] sent TLSv1.2 ChangeCipherSpec message (1 byte)
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.msg] sent TLSv1.2 'Finished' Handshake message (16 bytes)
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] ok: SSL negotiation finished successfully
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: SSL negotiation finished successfully
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: Server: XXXXXXX
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: TLSv1.2 connection created, using cipher ECDHE-RSA-AES256-SHA384 (256 bits)
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: passive backend data connection opened - local  : 46.16.73.69:47505
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: passive backend data connection opened - remote : 212.21.67.209:5029
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: starting TLS negotiation on data connection
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] (unknown): before/connect initialization
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: before/connect initialization
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.msg] sent TLSv1.2 'ClientHello' Handshake message (512 bytes)
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:37,975 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:38,013 mod_proxy/0.3[50041]: [tls.msg] sent TLSv1.2 fatal 'unexpected_message' Alert message (2 bytes)
2016-10-21 09:29:38,014 mod_proxy/0.3[50041]: [tls.info] writing: SSL/TLS alert fatal: unexpected_message
2016-10-21 09:29:38,014 mod_proxy/0.3[50041]: [tls.info] connecting: unknown state
2016-10-21 09:29:38,014 mod_proxy/0.3[50041]: unable to connect using TLS: protocol error:
  (1) error:140940F5:SSL routines:SSL3_READ_BYTES:unexpected record
2016-10-21 09:29:38,014 mod_proxy/0.3[50041]: unable to open data connection: TLS negotiation failed
2016-10-21 09:29:38,014 mod_proxy/0.3[50041]: postopen error for frontend data connection output stream: Operation not permitted
```

any hints?

regards
Andreas

**Comment by andreasfenzsw** [comment] 2016-10-21 09:45
I forgot.
Compiled against proftp 1.3.6rc2 on current debian/jessie with libssl 1.0.1t-1+deb8u5

**Comment by Castaglia** [comment] 2016-10-21 16:18
What FTPS client are you using?  The reason I ask is that these log messages:

    2016-10-21 09:29:24,519 mod_proxy/0.3[50041]: passive frontend data connection opened - remote : 127.0.0.1:44857
    2016-10-21 09:29:24,548 mod_proxy/0.3[50041]: [tls.msg] received TLSv1.2 warning 'close_notify' Alert message (2 bytes)
    2016-10-21 09:29:24,548 mod_proxy/0.3[50041]: [tls.info] reading: SSL/TLS alert warning: close notify

_suggest_ that `mod_proxy`, upon receiving the TCP connection from your client for the passive data connection, then receives a TLS alert _from_ the client, which in turn suggests that the _client_ is the one closing the connection for some reason.

**Comment by Castaglia** [comment] 2016-10-25 02:34
Interesting.  If I use:

    ProxyTLSProtocol ALL -SSLv3

_or_

    ProxyTLSProtocol ALL -TLSv1

then multiple directory listings work for me, locally.  _*But*_ if I use

    ProxyTLSProtocol ALL -SSLv3 -TLSv1

_then_ I see similar (but not _exactly_ the same) issues with multiple directory listings.

**Comment by Castaglia** [comment] 2016-10-25 02:39
What does the _rest_ of your `proftpd.conf` look like, too?  I just encountered a situation where I _thought_ I was reproducing your issue locally -- but then I realized that my `mod_tls` configuration, elsewhere in the `proftpd.conf`, was conflicting with my `mod_proxy.conf` configuration...

**Comment by andreasfenzsw** [comment] 2016-10-25 07:15
My very basic proftpd.conf:

`
ServerName                      "FTP proxy"
ServerType                      standalone
DefaultServer                   on
Port                            21
UseIPv6                         off
Umask                           022
MaxInstances                    30
User                            nobody
Group                           nogroup
AllowOverwrite          on
<Limit SITE_CHMOD>
  DenyAll
</Limit>
<IfModule mod_proxy.c>
  ProxyEngine on
  ProxyLog /var/log/modproxy.log
  ProxyTables /usr/local/var/ftp/proxy
  ProxyRole forward
  ProxyForwardMethod user@host
   ProxyTLSEngine on
   ProxyTLSOptions EnableDiags NoSessionCache
   ProxyTLSProtocol ALL -SSLv3 -TLSv1
   ProxyTLSVerifyServer off
  <Class forward-proxy>
    From 127.0.0.1/32
    ProxyForwardEnabled on
  </Class>
</IfModule>
`
The first test i did with ProxyTLSProtocol ALL -SSLv3
and without  "NoSessionCache"

It dosn't change anything playing with SSLProtocol for me. Tried "ProxyTLSProtocol TLSv1.2" also.

In the log it seems there is an new connection vor the second "ls"? The timeout logs:

`
 2016-10-25 07:02:22,216 mod_proxy/0.3[49580]: passive backend data connection opened - local  : 46.16.73.69:34488
2016-10-25 07:02:22,216 mod_proxy/0.3[49580]: passive backend data connection opened - remote : 212.21.67.209:5056
2016-10-25 07:02:22,216 mod_proxy/0.3[49580]: starting TLS negotiation on data connection
2016-10-25 07:02:22,216 mod_proxy/0.3[49580]: [tls.info] (unknown): before/connect initialization
2016-10-25 07:02:22,216 mod_proxy/0.3[49580]: [tls.info] connecting: before/connect initialization
2016-10-25 07:02:22,216 mod_proxy/0.3[49580]: [tls.msg] sent TLSv1.2 'ClientHello' Handshake message (512 bytes)
2016-10-25 07:02:22,217 mod_proxy/0.3[49580]: [tls.info] connecting: unknown state
2016-10-25 07:02:22,217 mod_proxy/0.3[49580]: [tls.info] connecting: unknown state
2016-10-25 07:02:22,244 mod_proxy/0.3[49580]: [tls.msg] sent TLSv1.2 fatal 'unexpected_message' Alert message (2 bytes)
2016-10-25 07:02:22,244 mod_proxy/0.3[49580]: [tls.info] writing: SSL/TLS alert fatal: unexpected_message
2016-10-25 07:02:22,244 mod_proxy/0.3[49580]: [tls.info] connecting: unknown state
2016-10-25 07:02:22,245 mod_proxy/0.3[49580]: unable to connect using TLS: protocol error:
  (1) error:140940F5:SSL routines:SSL3_READ_BYTES:unexpected record
2016-10-25 07:02:22,245 mod_proxy/0.3[49580]: unable to open data connection: TLS negotiation failed
2016-10-25 07:02:22,245 mod_proxy/0.3[49580]: postopen error for frontend data connection output stream: Operation not permitted
2016-10-25 07:11:37,961 mod_proxy/0.3[49542]: [tls] caching SSL session (471 bytes):
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: E01700002EAE34213A355B64544785A5C01A6ECFFCAD0EA39B64018548BF9BED
    Session-ID-ctx:
    Master-Key: 4DDF5C40AA6D76620E0FE730AC9227F1D2A58CD320761124E83378C6B8586A78D8F9F7E504C2C8EE80E9DEEF6860B34F
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1477378885
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

2016-10-25 07:12:22,472 mod_proxy/0.3[49580]: [tls] caching SSL session (471 bytes):
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-SHA384
    Session-ID: 59260000D253DB21C8B73584DDFE148266865A0AFFB8C37A2EFF364ADAB2C3B1
    Session-ID-ctx:
    Master-Key: D86955C2615C86EA4E3F9B8AF4A6CED952966A521343F1C8DC6259304057C6170C42550BE8D75B43A56F8BECDF44B1EE
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1477378923
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
hBMjU2IC0gRzIwHhcA
`

**Comment by Castaglia** [comment] 2016-10-26 14:56
Do you know what kind of FTP server is on the other side?  The destination server, that is?

**Comment by Castaglia** [comment] 2016-10-30 23:24
The referenced PR should fix your issues; it does for my local tests (once I was able to reproduce the problem locally).  Could you try it out for your setup?

**Comment by andreasfenzsw** [comment] 2016-11-02 09:11
The PR fixes the issue in my case. Thank you!
BTW the FTP-server seems to be a cruscftp (http://www.crushftp.com/) on Windows. Sorry for the late reply i was on  vaccation.

**Comment by Castaglia** [comment] 2016-11-08 07:43
PR merged to master.  Thanks (and I hope you had a good holiday).

**Closed by Castaglia** 2016-11-08 07:43 UTC
Labels: Bug
