### ISSUE TITLE
mod_proxy won't load as a shared module (RHEL9, proftpd 1.3.8b, mod_proxy 0.9.3, sqlite 3.34.1)

### ISSUE THREAD

**Issue by pzeidler-dlr** [Castaglia/proftpd-mod_proxy#267] opened 2024-03-21 12:04 UTC
I'm trying to build a proftpd-mod_proxy rpm for RHEL9.
I'm starting with the EPEL SRPM and adding mod_proxy.
if I add mod_proxy as a compiled-in module I can configure it and it's working, but if I try to build it as a shared_module I get a mod_proxy.so that according to strace gets found and mmaped, then libsqlite gets found and mmapped, and then mod_proxy and libsqlite get unmapped and proftpd says:
```
[root@geode x86_64]# /usr/sbin/proftpd --configtest
Checking syntax of configuration file
2024-03-21 11:21:18,540 geode proftpd[417585]: mod_dso/0.5: unable to load 'mod_proxy.c'; check to see if '/usr/libexec/proftpd/mod_proxy.la' exists
2024-03-21 11:21:18,540 geode proftpd[417585]: fatal: LoadModule: error loading module 'mod_proxy.c': No such file or directory on line 165 of '/etc/proftpd/modules.conf'
2024-03-21 11:21:18,540 geode proftpd[417585]: warning: unable to include '/etc/proftpd/modules.conf': Operation not permitted
Syntax check complete.
[root@geode x86_64]# ls -l /usr/libexec/proftpd/mod_proxy.so
-rwxr-xr-x. 1 root root 591024 Mar 20 17:55 /usr/libexec/proftpd/mod_proxy.so
```
I tried
```
LoadFile /lib64/libsqlite3.so
LoadModule mod_proxy.c
```
but that also didn't change the behaviour.

tracing dso:20 doesn't provide me enlightenment:
```
<dso:5>: loading module '/usr/libexec/proftpd/mod_proxy'
<dso:7>: looking for symbol 'proxy_module' in loaded module
<dso:1>: unable to find module symbol 'proxy_module' in 'self'
```
```
nm -D /usr/libexec/proftpd/mod_proxy.so gives
000000000008e004 D proxy_logfd
000000000008e4c0 D proxy_module
```
The build of mod_proxy, in either case, looks good, it only warns about unused variables and EVP_Cipher.
The system usually has sestatus enforcing, but sestatus permissive doesn't fix the loading of mod_proxy. Other modules load fine.

it configures
```
=== configuring in contrib/mod_proxy (/root/rpmbuild/BUILD/proftpd-1.3.8b/contrib/mod_proxy)
configure: running /bin/sh ./configure --disable-option-checking '--prefix=/usr'  '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--libexecdir=/usr/libexec/proftpd' '--localstatedir=/run/proftpd' '--disable-strip' '--enable-ctrls' '--enable-dso' '--enable-facl' '--enable-ipv6' '--enable-memcache' '--enable-nls' '--enable-openssl' '--disable-pcre' '--enable-pcre2' '--disable-redis' '--enable-shadow' '--enable-tests=nonetwork' '--with-libraries=/usr/lib64/mariadb' '--with-includes=/usr/include/mysql' '--with-modules=mod_readme:mod_auth_pam:mod_tls' '--with-shared=mod_sql:mod_sql_passwd:mod_sql_mysql:mod_sql_postgres:mod_sql_sqlite:mod_quotatab:mod_quotatab_file:mod_quotatab_ldap:mod_quotatab_radius:mod_quotatab_sql:mod_ldap:mod_ban:mod_ctrls_admin:mod_facl:mod_load:mod_vroot:mod_radius:mod_ratio:mod_rewrite:mod_site_misc:mod_exec:mod_shaper:mod_wrap2:mod_wrap2_file:mod_wrap2_sql:mod_copy:mod_deflate:mod_ifversion:mod_qos:mod_sftp:mod_sftp_pam:mod_sftp_sql:mod_tls_shmcache:mod_tls_memcache:mod_unique_id:mod_proxy:mod_ifsession' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CC=gcc' 'CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' 'LDFLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 ' 'CXX=g++' 'CXXFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--enable-ltdl-convenience' --cache-file=/dev/null --srcdir=.
```
and links:
```
libtool: link: gcc -shared  .libs/mod_proxy.o lib/proxy/.libs/random.o lib/proxy/.libs/db.o lib/proxy/.libs/dns.o lib/proxy/.libs/session.o lib/proxy/.libs/conn.o lib/proxy/.libs/netio.o lib/proxy/.libs/inet.o lib/proxy/.libs/str.o lib/proxy/.libs/ssh.o lib/proxy/ssh/.libs/db.o lib/proxy/ssh/.libs/redis.o lib/proxy/.libs/tls.o lib/proxy/tls/.libs/db.o lib/proxy/.libs/uri.o lib/proxy/.libs/forward.o lib/proxy/.libs/reverse.o lib/proxy/reverse/.libs/db.o lib/proxy/reverse/.libs/redis.o lib/proxy/ftp/.libs/conn.o lib/proxy/ftp/.libs/ctrl.o lib/proxy/ftp/.libs/data.o lib/proxy/ftp/.libs/dirlist.o lib/proxy/ftp/.libs/facts.o lib/proxy/ftp/.libs/msg.o lib/proxy/ftp/.libs/sess.o lib/proxy/ftp/.libs/xfer.o lib/proxy/ssh/.libs/agent.o lib/proxy/ssh/.libs/auth.o lib/proxy/ssh/.libs/bcrypt.o lib/proxy/ssh/.libs/cipher.o lib/proxy/ssh/.libs/compress.o lib/proxy/ssh/.libs/crypto.o lib/proxy/ssh/.libs/disconnect.o lib/proxy/ssh/.libs/interop.o lib/proxy/ssh/.libs/kex.o lib/proxy/ssh/.libs/keys.o lib/proxy/ssh/.libs/mac.o lib/proxy/ssh/.libs/misc.o lib/proxy/ssh/.libs/msg.o lib/proxy/ssh/.libs/packet.o lib/proxy/ssh/.libs/service.o lib/proxy/ssh/.libs/session.o lib/proxy/ssh/.libs/umac.o lib/proxy/ssh/.libs/umac128.o lib/proxy/ssh/.libs/utf8.o   -L/root/rpmbuild/BUILD/proftpd-1.3.8b/lib -L/usr/lib64/mariadb -lidn2 -lsodium -lsqlite3 -lssl -lcrypto -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -Wl,-soname -Wl,mod_proxy.so -o .libs/mod_proxy.so
lto-wrapper: warning: using serial compilation of 7 LTRANS jobs
```
Any suggestion on how to debug the issue would be great (a "you need to X not Y you dummy" even better)

**Comment by Castaglia** [comment] 2024-03-23 17:17
Nothing immediately jumps out as wrong.  My initial suspicion is something along the lines of `LD_RUNPATH` and/or `/etc/ld.so.conf` configuration.  But I'll want to reproduce this behavior locally to make sure; it could be something else entirely.

**Comment by Castaglia** [comment] 2024-03-23 17:34
This sounds somewhat similar to https://github.com/proftpd/proftpd/issues/1590, in terms of symptoms...

**Comment by Castaglia** [comment] 2024-03-23 17:47
What does this show, for you?
```
$ cat /usr/libexec/proftpd/mod_proxy.la
```

**Comment by Castaglia** [comment] 2024-03-23 20:23
In order for me to try reproducing this locally, can you provide the full set of instructions for installing the EPEL SRPM for ProFTPD, and then using that to configure/build mod_proxy as a DSO, that you are using?  I'm not an expert in RPMs, tending to use Debian/Ubuntu packages more.

**Comment by pzeidler-dlr** [comment] 2024-03-25 13:48
Thank you for looking at this.
I've compared the output of ldd /usr/sbin/proftpd of the proftpd that has mod_proxy compiled in (and is using it successfully) and the proftpd binary without, and the only lib they differ by is libsqlite3.so.0, which mod_dso loads when it loads mod_proxy according to strace. 

I'm by no means an expert on RPM building either. This is frankly an exercise between cargo-culting and digging through manpages.

You'll need:
```
# rpmbuild
dnf install rpm-build
# build dependencies of proftpd and its modules
dnf install check-devel libacl-devel libcap-devel libidn2-devel libmemcached-devel libpq-devel libsodium-devel mariadb-connector-c-devel ncurses-devel openldap-devel openssl-devel pam-devel pcre2-devel perl-Crypt-Cracklib perl-generators sqlite-devel zlib-devel 
# fetch the src rpm, eg to /var/tmp
cd /var/tmp
wget https://dl.fedoraproject.org/pub/epel/9/Everything/source/tree/Packages/p/proftpd-1.3.8b-2.el9.src.rpm
# install using rpm -i, it creates a /root/rpmbuild directory with the proftpd rpm build environment
rpm -i /var/tmp/proftpd-1.3.8b-2.el9.src.rpm
cd /root/rpmbuild/SOURCES
# get the mod_proxy source
wget https://github.com/Castaglia/proftpd-mod_proxy/archive/refs/tags/v0.9.3.tar.gz
# unpack cacerts.pem
tar xzf v0.9.3.tar.gz proftpd-mod_proxy-0.9.3/cacerts.pem
mv proftpd-mod_proxy-0.9.3/cacerts.pem cacerts.pem && rmdir proftpd-mod_proxy-0.9.3
# apply the patch
cd /root/rpmbuild
patch -p1 < proftpd-rpmbuild-4mod_proxy.patch
# build the rpms
rpmbuild -bb SPECS/proftpd.spec
```

 I'm building with the mkdir-race patch because we need it, but I don't believe that it's actually
 relevant to this issue, I'm just including it for completeness sake.
Likewise I've moved cacerts.pem into /etc/proftpd for cosmetic reasons, and it's also rather
unlikly to matter.

and the patch file:
[proftpd-rpmbuild-4mod_proxy.patch](https://github.com/Castaglia/proftpd-mod_proxy/files/14744324/proftpd-rpmbuild-4mod_proxy.patch)

**Comment by Castaglia** [comment] 2024-03-26 01:52
Thanks for that!  I ran those instructions, with one minor change:
```
rpmbuild -bb --noclean SPECS/proftpd.spec
```
This leaves the `BUILD/proftpd-1.3.8b/` directory around, so that I can more easily examine the compiled files.

First, I wanted to see what `ldd` showed for a "working" shared module, like mod_sftp:
```
[root@833bbf3acc46 proftpd-1.3.8b]# ldd contrib/mod_sftp/.libs/mod_sftp.so 
	linux-vdso.so.1 (0x00007fff0f6a3000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f330abe7000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f330abc6000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f330ab6d000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f330a73b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f330a532000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f330a3ad000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f330ac94000)
```
In order to compare it with mod_proxy:
```
[root@833bbf3acc46 proftpd-1.3.8b]# ldd contrib/mod_proxy/.libs/mod_proxy.so 
	linux-vdso.so.1 (0x00007ffde08ba000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f9bf59bf000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007f9bf5966000)
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f9bf582e000)
	libssl.so.3 => /lib64/libssl.so.3 (0x00007f9bf5788000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007f9bf5356000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9bf514d000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f9bf4fc6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9bf5a76000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9bf4eeb000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f9bf4ed1000)
```
That looks as I'd expect.

So then I installed the compiled files directly:
```
cd /root/rpmbuild/BUILD/proftpd-1.3.8b
make install
```
And used it on a simple test config file in `/tmp/test.conf`:
```
<IfModule mod_dso.c>
  LoadModule mod_proxy.c
</IfModule>
```
And sure enough, there's the issue:
```
[root@833bbf3acc46 proftpd-1.3.8b]# /usr/sbin/proftpd -td10 -c /tmp/test.conf
Checking syntax of configuration file
2024-03-26 01:50:02,138 833bbf3acc46 proftpd[21143]: using PCRE2 10.40
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: using TCP receive buffer size of 87380 bytes
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: using TCP send buffer size of 16384 bytes
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: using 'C.utf8' locale based on LANG=C.utf8 environment variable
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: using 'UTF-8' as local charset for UTF-8 conversion
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: mod_tls/2.9.2: using OpenSSL 3.0.7 1 Nov 2022
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: <IfModule>: using 'mod_dso.c' section at line 1
2024-03-26 01:50:02,140 833bbf3acc46 proftpd[21143]: mod_dso/0.5: loading 'mod_proxy.c'
2024-03-26 01:50:02,143 833bbf3acc46 proftpd[21143]: mod_dso/0.5: unable to dlopen 'mod_proxy.c': file not found (No such file or directory)
2024-03-26 01:50:02,143 833bbf3acc46 proftpd[21143]: mod_dso/0.5: unable to load 'mod_proxy.c'; check to see if '/usr/libexec/proftpd/mod_proxy.la' exists
2024-03-26 01:50:02,143 833bbf3acc46 proftpd[21143]: mod_dso/0.5: defaulting to 'self' for symbol resolution
2024-03-26 01:50:02,143 833bbf3acc46 proftpd[21143]: mod_dso/0.5: unable to find module symbol 'proxy_module' in 'self'
2024-03-26 01:50:02,143 833bbf3acc46 proftpd[21143]: fatal: LoadModule: error loading module 'mod_proxy.c': No such file or directory on line 2 of '/tmp/test.conf'
```

I don't know what the cause is yet, but reproducing it locally will definitely help!

**Comment by Castaglia** [comment] 2024-03-26 02:06
I _think_ that https://github.com/Castaglia/proftpd-mod_proxy/pull/269 may help.  It's something I noticed, when comparing the generated `Makefile` for mod_sftp (which works) with the generated `Makefile` for mod_proxy (which doesn't).  The mod_proxy module does use zlib (for SFTP compression), as well as DNS resolver versions from `libresolv`.  If those libraries aren't properly specified, when linking the `.so`, then the dynamic loader wouldn't know to include those libraries, which in turn would lead to unsatisfied symbol resolution, which could cause this bug.

**Comment by Castaglia** [comment] 2024-03-26 16:28
Hmm.  Using my local setup and the above patch, I still see the same failure when ProFTPD attempts to load mod_proxy as a shared module.  But the `ldd` output at least shows that the additional libraries are being linked as expected:
```
[root@833bbf3acc46 proftpd-1.3.8b]# ldd /usr/libexec/proftpd/mod_proxy.so
	linux-vdso.so.1 (0x00007ffc15de4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fcc9430d000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fcc942f9000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007fcc942d8000)
	libsodium.so.23 => /lib64/libsodium.so.23 (0x00007fcc9427f000)
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007fcc94147000)
	libssl.so.3 => /lib64/libssl.so.3 (0x00007fcc940a1000)
	libcrypto.so.3 => /lib64/libcrypto.so.3 (0x00007fcc93c6d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fcc93a64000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007fcc938df000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcc943bd000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fcc93804000)
```

**Comment by Castaglia** [comment] 2024-03-27 03:36
OK, I think I've found a promising lead in this old (but still pertinent) email thread:
* https://bug-libtool.gnu.narkive.com/eWFGvX8k/misleading-error-message-from-lt-dlopen

It may take me a little while to use that info to suss out all of the issues involved here.

**Comment by Castaglia** [comment] 2024-03-27 03:45
> OK, I think I've found a promising lead in this old (but still pertinent) email thread:
> 
> * https://bug-libtool.gnu.narkive.com/eWFGvX8k/misleading-error-message-from-lt-dlopen
> 
> It may take me a little while to use that info to suss out all of the issues involved here.

Success!  I had to hack on the bundled libltdl code (which handles the dynamic loader bits), adding some instrumentation to get the _real_ error, eventually getting this clue:
```
$ /usr/sbin/proftpd -td10 -c /tmp/test.conf
...
Calling lt_dlopen->module_open (/usr/libexec/proftpd/mod_proxy.so)
dlopen error: /usr/libexec/proftpd/mod_proxy.so: undefined symbol: proxy_tls_redis_as_datastore
```
And we can confirm this, too:
```
[root@833bbf3acc46 proftpd-1.3.8b]# nm /usr/libexec/proftpd/mod_proxy.so | grep proxy_tls
0000000000034820 T proxy_tls_db_as_datastore
0000000000034770 T proxy_tls_free
0000000000033110 T proxy_tls_get_errors
0000000000034890 T proxy_tls_init
0000000000034630 T proxy_tls_match_client_tls
                 U proxy_tls_redis_as_datastore
0000000000037c50 T proxy_tls_sess_free
0000000000035910 T proxy_tls_sess_init
00000000000345d0 T proxy_tls_set_data_prot
00000000000345f0 T proxy_tls_set_tls
0000000000030250 t proxy_tls_shutdown_ev
0000000000034620 T proxy_tls_using_tls
```
This lead me to double-check the generated Makefile for mod_proxy -- and I found that, indeed, the object file providing that function/symbol was present for static module builds, but was not in the list of object files for shared module builds.

I verified this fix locally, and have updated https://github.com/Castaglia/proftpd-mod_proxy/pull/269 accordingly.  It should work for you now.

**Comment by pzeidler-dlr** [comment] 2024-03-27 07:26
Adding proxy_tls_redis.lo to SHARE_MODULE_OBJS makes the shared module work.
Adding $(MODULE_LIBS) to its linking isn't necessary to make it work.

Thanks a bundle!

**Comment by Castaglia** [comment] 2024-03-28 01:12
This should now be fixed in master.  I've also created a new release with this fix.  Thanks!

**Closed by Castaglia** 2024-03-28 01:12 UTC
Labels: Build
