### ISSUE TITLE
Data Upload Fails after around 200k

### ISSUE THREAD

**Issue by mikepultz** [Castaglia/proftpd-mod_proxy#131] opened 2018-07-23 04:55 UTC
Hello,

I've set up mod_proxy with ProFTPD 1.3.6, as a reverse proxy to another ProFTPD instance on another server.

Downloading files seems to be fine- and uploading directly to the other ProFTPD instance works fine- but when I upload a file via the proxy, I receive this error in the proxy log:

```
2018-07-23 04:43:44,703 mod_proxy/0.5[14754]: error writing 16384 bytes of data to destination data connection: Success
2018-07-23 04:43:44,703 mod_proxy/0.5[14754]: unable to proxy data between frontend/backend, closing data connections
```
From my FTP client (FileZilla) I see:

```
Status:	Starting upload of C:\Users\Mike\Desktop\ps.zip
Command:	CWD /
Response:	250 CWD command successful
Command:	PWD
Response:	257 "/" is the current directory
Command:	TYPE I
Response:	200 Type set to I
Command:	PASV
Response:	227 Entering Passive Mode (18,206,181,1,249,138).
Command:	STOR ps.zip
Response:	150 Opening BINARY mode data connection for ps.zip
Response:	226 Transfer complete
Error:	File transfer failed after transferring 196,608 bytes in 1 second
```

and then it retries several times.

Any thoughts would be appreciated!

Mike

**Comment by mikepultz** [comment] 2018-07-23 15:00
Here is my current configuration:

```
ServerName      "Test FTP Server"
ServerType      standalone
DefaultServer   on
DefaultAddress  192.168.100.110
Port            21

UseIPv6         off
Umask           022
MaxInstances    30
User            root
Group           root
DefaultRoot     ~
UseReverseDNS   off
ScoreboardFile  /var/run/proftpd.pid
SyslogLevel     debug
SyslogFacility  LOCAL4
TransferLog     /u/logs/ftp/transfer.log

LogFormat       default "%h %l %u %t \"%r\" %s %b"
LogFormat       auth    "%v [%P] %h %t \"%r\" %s"
LogFormat       write   "%h %l %u %t \"%r\" %s %b"

AllowStoreRestart   on
PassivePorts        60000 65535
AllowForeignAddress on
MasqueradeAddress   x.x.x.x # public IP

#
# Global settings
#
<Directory /*>
    AllowOverwrite yes
</Directory>

#
# TLS
#
TLSEngine on
TLSProtocol SSLv3 TLSv1
TLSRequired off
TLSVerifyClient off
TLSRenegotiate none
TLSCipherSuite ALL:!ADH:RC4+RSA:+HIGH:+MEDIUM:-LOW:-SSLv2:-EXP
TLSRSACertificateFile /etc/certs/domain.ca.pem
TLSRSACertificateKeyFile /etc/certs/domain.ca.key

#
# Proxy
#
ProxyEngine on
ProxyLog /u/logs/ftp/proxy.log
ProxyTables /tmp/proxy.table

ProxyRole reverse
ProxyReverseConnectPolicy RoundRobin
#ProxyReverseServers ftp://76.9.192.78:21 ftp://76.9.192.79:21
ProxyReverseServers ftp://76.9.192.78:21                     
ProxyTLSVerifyServer off
```

**Comment by Castaglia** [comment] 2020-04-05 17:40
I wonder if this is related to https://github.com/proftpd/proftpd/issues/959.  Is your FTPS client using TLSv1.3, perhaps?

**Comment by Castaglia** [comment] 2020-05-30 16:35
Hmm.  I'm not able to reproduce this locally.  @mikepultz is still an issue for you, using the latest `mod_proxy` code?

**Comment by Castaglia** [comment] 2023-08-12 23:36
If there's nothing more to add to this ticket, I'd like to close it.

**Closed** 2024-09-14 15:05 UTC
Labels: Bug, Waiting for feedback
