### ISSUE TITLE
ProFTPD terminating (signal 11) if json file for user does not exist

### ISSUE THREAD

**Issue by robertpenz** [Castaglia/proftpd-mod_proxy#61] opened 2016-04-06 14:15 UTC
proftpd is segfaulting (ProFTPD terminating (signal 11)) if ProxyReverseServers file:/var/ftp/ftpproxy/backends/%U.json is configured and the file does not exist.

Debug log does not show much.
```
2016-04-06 15:55:16,201 [1733] <proxy:9>: removed PRE_CMD APPE mod_xfer handlers
2016-04-06 15:55:16,201 [1733] <proxy:9>: removed PRE_CMD RETR mod_xfer handlers
2016-04-06 15:55:16,201 [1733] <proxy:9>: removed PRE_CMD STOR mod_xfer handlers
2016-04-06 15:55:16,201 [1733] <proxy:9>: removed PRE_CMD STOU mod_xfer handlers
2016-04-06 15:55:16,217 [1733] <proxy.db:17>: (sqlite3): SELECT backend_uri FROM proxy_reverse.proxy_vhost_reverse_per_user WHERE vhost_id = 3 AND user_name = 'PrinzessinCelestia';
2016-04-06 15:55:16,218 [1733] <proxy.db:13>: successfully executed 'SELECT backend_uri FROM proxy_reverse.proxy_vhost_reverse_per_user WHERE vhost_id = ? AND user_name = ?;'
2016-04-06 15:55:16,218 [1733] <proxy.reverse:17>: loading user-specific ProxyReverseServers file '/var/dvt/ftpproxy/backends/PrinzessinCelestia.json'
2016-04-06 15:55:16,218 [1733] <proxy.reverse:18>: no 'sql_lookup' symbol found (mod_sql not loaded?), skipping per-user SQL lookups
2016-04-06 15:55:16,218 [1733] <proxy.reverse:11>: using global ProxyReverseServers list for user 'PrinzessinCelestia'
2016-04-06 13:55:21,142 [1682] <proxy:15>: found group 'NONE' for command 'REST'
2016-04-06 13:55:22,072 [1682] <proxy:15>: found group 'NONE' for command 'TYPE'
2016-04-06 13:55:22,077 [1682] <proxy:17>: accepting connection from backend server for active data transfer for LIST
2016-04-06 13:55:22,077 [1682] <proxy:17>: accepting connection from frontend server for passive data transfer for LIST
2016-04-06 13:55:22,100 [1682] <proxy:19>: handling data connection during data transfer
2016-04-06 13:55:22,100 [1682] <proxy:9>: received 5199 bytes of data from source data connection
2016-04-06 13:55:22,100 [1682] <proxy:19>: handling data connection during data transfer
2016-04-06 13:55:22,100 [1682] <proxy:19>: read EOF on data connection, closing frontend/backend data connections
2016-04-06 13:55:52,576 [1682] <proxy:15>: found group 'NONE' for command 'TYPE'
2016-04-06 15:56:02,010 [1734] <proxy.db:18>: finished prepared statement 'INSERT INTO proxy_tls.proxy_tls_vhosts (vhost_id, vhost_name) VALUES (?, ?);'
2016-04-06 15:56:02,012 [1734] <proxy.db:18>: finished prepared statement 'SELECT version FROM proxy_tls.schema_version WHERE schema = ?;'
2016-04-06 15:56:02,012 [1734] <proxy.db:18>: finished prepared statement 'INSERT INTO proxy_reverse.proxy_vhost_reverse_roundrobin (vhost_id, current_backend_id) VALUES (?, ?);'
2016-04-06 15:56:02,012 [1734] <proxy.db:18>: finished prepared statement 'INSERT INTO proxy_reverse.proxy_vhosts (vhost_id, vhost_name) VALUES (?, ?);'
2016-04-06 15:56:02,012 [1734] <proxy.db:18>: finished prepared statement 'SELECT version FROM proxy_reverse.schema_version WHERE schema = ?;'
2016-04-06 15:56:02,053 [1734] <proxy.db:18>: closed SQLite database
2016-04-06 15:56:02,055 [1734] <proxy.db:9>: opened SQLite table '/var/ftp/proxy/proxy-reverse.db' (schema 'proxy_reverse')
2016-04-06 15:56:02,056 [1734] <proxy.db:17>: (sqlite3): ATTACH DATABASE '/var/ftp/proxy/proxy-reverse.db' AS proxy_reverse;
2016-04-06 15:56:02,061 [1734] <proxy.db:17>: (sqlite3): PRAGMA proxy_reverse.journal_mode = MEMORY;
2016-04-06 15:56:02,061 [1734] <proxy.db:17>: (sqlite3): SELECT version FROM proxy_reverse.schema_version WHERE schema = 'proxy_reverse';
2016-04-06 15:56:02,062 [1734] <proxy.db:12>: executing prepared statement 'SELECT version FROM proxy_reverse.schema_version WHERE schema = ?;' returned row (columns: 1)
2016-04-06 15:56:02,062 [1734] <proxy.db:17>: column version [0]: 1
2016-04-06 15:56:02,062 [1734] <proxy.db:13>: successfully executed 'SELECT version FROM proxy_reverse.schema_version WHERE schema = ?;'
2016-04-06 15:56:02,062 [1734] <proxy.db:11>: schema version 1 >= desired version 1 for schema 'proxy_reverse'
2016-04-06 15:56:02,062 [1734] <proxy:9>: removed PRE_CMD APPE mod_xfer handlers
2016-04-06 15:56:02,062 [1734] <proxy:9>: removed PRE_CMD RETR mod_xfer handlers
2016-04-06 15:56:02,062 [1734] <proxy:9>: removed PRE_CMD STOR mod_xfer handlers
2016-04-06 15:56:02,062 [1734] <proxy:9>: removed PRE_CMD STOU mod_xfer handlers
```

**Comment by Castaglia** [comment] 2016-04-06 18:19
Hrm.  I thought I'd fixed this in the latest/greatest code in the master branch; has it regressed?  Let me reproduce this locally...

**Comment by Castaglia** [comment] 2016-04-06 18:52
This should now be fixed in master.  Thanks for catching/reporting this!

Now the behavior is better (but not great); rather than segfaulting (due to null pointer dereference), you'll see:

    500 USER: Operation not permitted

as the FTP response.  And `mod_proxy` will log about the lack of fallback/global `ProxyReverseServers`, when a per-user/per-group file cannot be found.

**Comment by robertpenz** [comment] 2016-04-07 06:50
Works now:

```
<--- 200 Using default language en_US
---> OPTS UTF8 ON
<--- 200 UTF8 set to on
---> HOST 10.x.x.x
<--- 220 HOST command successful
---> USER user.name.
<--- 500 USER: Operation not permitted
---> QUIT
---- Closing control socket
ls: ls: Login failed: 500 USER: Operation not permitted
```

but I'm not sure if there is not something else now.

1. I don't get the message about a lacking fallback ProxyReverseServers
2. I does ignore my fallback ProxyReverseServers 

config is as follows:

```
ProxyEngine on
ProxyLog /var/log/ftpproxy.log
ProxyTables /var/ftp/proxy
# We need to provide a pool of backend servers as a fallback
ProxyReverseServers ftp://10.x.x.x:21
TraceLog /var/log/proxy-trace.log
Trace proxy:20 proxy.reverse:20 proxy.db:20

<VirtualHost 10.x.x.x>
  ServerName "server EXT"
  MasqueradeAddress x.x.x.x

  ProxyEngine on
  ProxyRole reverse
  ProxyReverseConnectPolicy PerUser
  ProxyDataTransferPolicy active
  ProxyTLSEngine off
  ProxySourceAddress 10.x.x.x
  # Look up per-user backend servers from user-specific JSON files
  ProxyReverseServers file:/var/ftp/ftpproxy/backends/%U.json
</VirtualHost>


<VirtualHost 10.x.x.x>
  ServerName "server INT"

  ProxyEngine on
  ProxyRole reverse
  ProxyReverseConnectPolicy PerUser
  ProxyDataTransferPolicy active
  ProxyTLSEngine off
  ProxySourceAddress 10.x.x.x

  # Look up per-user backend servers from user-specific JSON files
  ProxyReverseServers file:/var/ftp/ftpproxy/backends/%U.json
</VirtualHost>
```

**Comment by Castaglia** [comment] 2016-04-07 14:54
Unlike Apache, configuration directives in ProFTPD that are outside of any `<VirtualHost>` section are *not* global.  Thus to make your fallback `ProxyReverseServers` list globally applied to your two vhosts, you would need to put it in a `<Global>` section:

    <Global>
      # We need to provide a pool of backend servers as a fallback
      ProxyReverseServers ftp://10.x.x.x:21
    </Global>

**Comment by robertpenz** [comment] 2016-04-08 07:21
That does not work for me. If I place a server which does not exists in the Global option, I run into a timeout even if the user is in the json file with a correct server.  It seems the global option takes precedence.

**Comment by Castaglia** [comment] 2016-04-08 18:27
Right; the use of `<Global>` is just an easy way to provide a fallback for all vhosts, _assuming that fallback exists for all vhosts_.  If not, then you'd need to configure a `ProxyReverseServers` fallback within each individual `<VirtualHost>` section, in addition to the per-user `ProxyReverseServers`, that is appropriate to that vhost.

I'll reproduce the behavior you mentioned, of a valid per-user JSON file not being honored above the fallback server.

**Comment by Castaglia** [comment] 2016-04-12 17:58
I encountered several issues while reproducing this, and fixed them: database uniqueness constraints, buggy handling of the global/fallback servers, etc.  These should be fixed now in master.

**Comment by robertpenz** [comment] 2016-04-13 07:38
now it does not start anymore

```
[root@servername rpm]# proftpd -d10 -n             
2016-04-13 09:33:57,657 servername proftpd[4151]: using PCRE 8.32 2012-11-30
2016-04-13 09:33:57,662 servername proftpd[4151]: using TCP receive buffer size of 87380 bytes
2016-04-13 09:33:57,662 servername proftpd[4151]: using TCP send buffer size of 16384 bytes
2016-04-13 09:33:57,662 servername proftpd[4151]: testing Unix domain socket using S_ISFIFO
2016-04-13 09:33:57,662 servername proftpd[4151]: testing Unix domain socket using S_ISSOCK
2016-04-13 09:33:57,662 servername proftpd[4151]: using S_ISSOCK macro for Unix domain socket detection
2016-04-13 09:33:57,663 servername proftpd[4151]: mod_tls/2.7: using OpenSSL 1.0.1e-fips 11 Feb 2013
2016-04-13 09:33:57,666 servername proftpd[4151]: mod_memcache/0.1: using libmemcached-1.0.16
2016-04-13 09:33:57,667 servername proftpd[4151]: using 'UTF-8' as local charset for UTF-8 conversion
2016-04-13 09:33:57,669 servername proftpd[4151]: retrieved UID 99 for user 'nobody'
2016-04-13 09:33:57,669 servername proftpd[4151]: retrieved GID 99 for group 'nobody'
2016-04-13 09:33:57,670 servername proftpd[4151]: ROOT PRIVS at trace.c:352
2016-04-13 09:33:57,671 servername proftpd[4151]: RELINQUISH PRIVS at trace.c:355
2016-04-13 09:33:57,671 servername proftpd[4151]: ROOT PRIVS at mod_tls.c:11757
2016-04-13 09:33:57,672 servername proftpd[4151]: RELINQUISH PRIVS at mod_tls.c:11759
2016-04-13 09:33:57,672 servername proftpd[4151]: ROOT PRIVS at mod_tls.c:11780
2016-04-13 09:33:57,673 servername proftpd[4151]: RELINQUISH PRIVS at mod_tls.c:11782
2016-04-13 09:33:57,673 servername proftpd[4151]: mod_tls/2.7: NoCertRequest TLSOption is deprecated
2016-04-13 09:33:57,673 servername proftpd[4151]: <IfModule>: skipping 'mod_tls_shmcache.c' section at line 66
2016-04-13 09:33:57,685 servername proftpd[4151]: UseReverseDNS off, returning IP address instead of DNS name
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: 
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: Config for ProFTPD:
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: ServerIdent
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: UserID
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: UserName
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: GroupID
2016-04-13 09:33:57,685 servername proftpd[4151] 10.x.x.x.x: GroupName
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: LogFormat
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: LogFormat
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: ProxyEngine
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: ProxyLog
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: ProxyTables
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: AllowOverwrite
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: PassivePorts
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: FactsAdvertise
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: UseSendfile
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: TLSEngine
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: TLSRequired
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: TLSProtocol
2016-04-13 09:33:57,686 servername proftpd[4151] 10.x.x.x.x: TLSRSACertificateFile
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: TLSRSACertificateKeyFile
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: TLSCipherSuite
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: TLSOptions
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: TLSVerifyClient
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: TLSRenegotiate
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: TLSLog
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: UseReverseDNS off, returning IP address instead of DNS name
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: 10.x.x.y:21 masquerading as z.z.z.z
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: 
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: Config for servername EXT:
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: MasqueradeAddress
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: ProxyEngine
2016-04-13 09:33:57,687 servername proftpd[4151] 10.x.x.x.x: ProxyRole
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: ProxyReverseConnectPolicy
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: ProxyDataTransferPolicy
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: ProxyTLSEngine
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: ProxySourceAddress
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: ProxyReverseServers
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: AllowOverwrite
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: PassivePorts
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: FactsAdvertise
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: UseSendfile
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: TLSEngine
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: TLSRequired
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: TLSProtocol
2016-04-13 09:33:57,688 servername proftpd[4151] 10.x.x.x.x: TLSRSACertificateFile
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: TLSRSACertificateKeyFile
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: TLSCipherSuite
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: TLSOptions
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: TLSVerifyClient
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: TLSRenegotiate
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: TLSLog
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: 
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: Config for servername INT:
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: ProxyEngine
2016-04-13 09:33:57,689 servername proftpd[4151] 10.x.x.x.x: ProxyRole
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: ProxyReverseConnectPolicy
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: ProxyDataTransferPolicy
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: ProxyTLSEngine
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: ProxySourceAddress
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: ProxyReverseServers
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: AllowOverwrite
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: PassivePorts
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: FactsAdvertise
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: UseSendfile
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: TLSEngine
2016-04-13 09:33:57,690 servername proftpd[4151] 10.x.x.x.x: TLSRequired
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSProtocol
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSRSACertificateFile
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSRSACertificateKeyFile
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSCipherSuite
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSOptions
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSVerifyClient
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSRenegotiate
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: TLSLog
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: mod_lang/1.1: binding to text domain 'proftpd' using locale path '/usr/share/locale'
2016-04-13 09:33:57,691 servername proftpd[4151] 10.x.x.x.x: mod_lang/1.1: using locale files in '/usr/share/locale'
2016-04-13 09:33:58,111 servername proftpd[4151] 10.x.x.x.x: mod_lang/1.1: added the following supported languages: en_US, bg_BG, es_ES, ru_RU, zh_TW, fr_FR, zh_CN, ko_KR, ja_JP, it_IT
2016-04-13 09:33:58,111 servername proftpd[4151] 10.x.x.x.x: ROOT PRIVS at mod_ctrls.c:1208
2016-04-13 09:33:58,111 servername proftpd[4151] 10.x.x.x.x: RELINQUISH PRIVS at mod_ctrls.c:1210
2016-04-13 09:33:58,111 servername proftpd[4151] 10.x.x.x.x: ROOT PRIVS at lib/proxy/reverse.c:2502
2016-04-13 09:33:58,116 servername proftpd[4151] 10.x.x.x.x: RELINQUISH PRIVS at lib/proxy/reverse.c:2506
2016-04-13 09:33:58,185 servername proftpd[4151] 10.x.x.x.x: ProFTPD terminating (signal 11)
2016-04-13 09:33:58,185 servername proftpd[4151] 10.x.x.x.x: ROOT PRIVS at signals.c:57
2016-04-13 09:33:58,186 servername proftpd[4151] 10.x.x.x.x: RELINQUISH PRIVS at signals.c:83
2016-04-13 09:33:58,186 servername proftpd[4151] 10.x.x.x.x: ProFTPD 1.3.6rc2 standalone mode SHUTDOWN
2016-04-13 09:33:58,186 servername proftpd[4151] 10.x.x.x.x: ROOT PRIVS at signals.c:90
2016-04-13 09:33:58,186 servername proftpd[4151] 10.x.x.x.x: RELINQUISH PRIVS at signals.c:92
```

```
[root@servername rpm]# journalctl -xe
Apr 13 09:33:19 servername systemd[1]: Unit proftpd.service entered failed state.
Apr 13 09:33:19 servername systemd[1]: proftpd.service failed.
Apr 13 09:33:44 servername systemd[1]: Starting ProFTPD FTP Server...
-- Subject: Unit proftpd.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit proftpd.service has begun starting up.
Apr 13 09:33:44 servername proftpd[4142]: 2016-04-13 09:33:44,249 servername proftpd[4142]: mod_tls/2.7: NoCertRequest TLSOption is deprecated
Apr 13 09:33:44 servername proftpd[4142]: 2016-04-13 09:33:44,262 servername proftpd[4142] 10.x.x.x: 10.x.x.y:21 masquerading as z.z.z.z
Apr 13 09:33:44 servername proftpd[4142]: 2016-04-13 09:33:44,370 servername proftpd[4142] 10.x.x.x: ProFTPD terminating (signal 11)
Apr 13 09:33:44 servername proftpd[4142]: 2016-04-13 09:33:44,370 servername proftpd[4142] 10.x.x.x: ProFTPD 1.3.6rc2 standalone mode SHUTDOWN
Apr 13 09:33:44 servername systemd[1]: PID file /run/proftpd/proftpd.pid not readable (yet?) after start.
Apr 13 09:33:44 servername systemd[1]: proftpd.service never wrote its PID file. Failing.
Apr 13 09:33:44 servername systemd[1]: Failed to kill control group: Invalid argument
Apr 13 09:33:44 servername systemd[1]: Failed to kill control group: Invalid argument
Apr 13 09:33:44 servername systemd[1]: Failed to start ProFTPD FTP Server.
-- Subject: Unit proftpd.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit proftpd.service has failed.
-- 
-- The result is failed.
Apr 13 09:33:44 servername systemd[1]: Unit proftpd.service entered failed state.
Apr 13 09:33:44 servername systemd[1]: proftpd.service failed.
```

**Comment by Castaglia** [comment] 2016-04-13 15:32
Hrm.  Could you provide the entire config that you're currently using?  Looks like something is causing a segfault:

    ProFTPD terminating (signal 11)

**Comment by robertpenz** [comment] 2016-04-18 08:00
I sent you the full config file why email.

**Comment by robertpenz** [comment] 2016-04-19 06:36
the new version does not crash at startup

**Comment by Castaglia** [comment] 2016-04-19 06:42
Excellent!  I'm going to consider this issue closed, then.  Thanks!

**Closed by Castaglia** 2016-04-19 06:42 UTC
Labels: Bug

**Comment by robertpenz** [comment] 2016-04-19 08:54
thx, no crash now at startup but if I uncomment the like 38 I get

`Apr 19 08:45:53 xxxxxxx proftpd[4827]: 2016-04-19 08:45:53,519 vwebclb proftpd[4827]: fatal: ProxyReverseServers: error parsing 'ftp://10.xx.xx.xxx:21': Invalid argument on line 38 of '/etc/proftpd.conf'`
